/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from 'ethers';
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from '@nomicfoundation/hardhat-ethers/types';

import * as Contracts from './index.js';

declare module '@nomicfoundation/hardhat-ethers/types' {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: 'UserVault',
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UserVault__factory>;
    getContractFactory(
      name: 'VaultFactory',
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VaultFactory__factory>;

    getContractAt(
      name: 'UserVault',
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.UserVault>;
    getContractAt(
      name: 'VaultFactory',
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VaultFactory>;

    deployContract(
      name: 'UserVault',
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.UserVault>;
    deployContract(
      name: 'VaultFactory',
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VaultFactory>;

    deployContract(
      name: 'UserVault',
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.UserVault>;
    deployContract(
      name: 'VaultFactory',
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VaultFactory>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
