# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: Envioindexer
networks:
- id: 84532
  start_block: 0
  contracts:
  - name: UserVault
    address:
    - 0xd36094fC3D833861bf8E231842B4eeac1F79973D
    handler: src/EventHandlers.ts
    events:
    - event: AutoSyncTriggered(address indexed token, uint256 timestamp)
    - event: BalanceSynced(address indexed token, uint256 oldBalance, uint256 newBalance, uint256 timestamp)
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: TokenAdded(address indexed token, uint256 timestamp)
    - event: TokenRemoved(address indexed token, uint256 timestamp)
    - event: TokensReceived(address indexed token, uint256 amount, address indexed from, uint256 timestamp)
    - event: TokensWithdrawn(address indexed token, uint256 amount, address indexed to, uint256 timestamp)
unordered_multichain_mode: true
preload_handlers: true
